jenkins:
  image: jenkins
  ports:
    - "18080:8080"
  expose:
    - 18080
  links:
    - gitlab:gitlab
    - sonar:sonar
  environment:
    VIRTUAL_HOST: ci.trader.community
    LETSENCRYPT_EMAIL: admin@rails-experts.com
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/bin/docker

sonar:
  build: ./sonar
  ports:
   - "19000:9000"
   - "5432:5432"
  expose:
    - 19000
  environment:
    LETSENCRYPT_EMAIL: admin@rails-experts.com
    SONARQUBE_JDBC_URL: "jdbc:postgresql://localhost:5432/sonar"
    VIRTUAL_HOST: sonar.trader.community
db:
  image: postgres
  net: container:sonar
  environment:
    POSTGRES_USER: sonar
    POSTGRES_PASSWORD: sonar

postgresql:
  image: sameersbn/postgresql:9.4-3
  environment:
    DB_USER: gitlab
    DB_PASS: gh2016pw!
    DB_NAME: gitlabhq_production
  volumes:
    - /home/deploy/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:latest
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  expose:
    - 10080
  environment:
    LETSENCRYPT_EMAIL: admin@rails-experts.com
    VIRTUAL_HOST: git.trader.community
    TZ: Europe/Berlin
    GITLAB_TIMEZONE: Berlin

    GITLAB_SECRETS_DB_KEY_BASE: 2rBNjLjXwpnMlpHVSKxcSCNmgvfFVPg4NWj3lMQ7fXMTbqMrWDrLTcNtBHdwxX4C

    GITLAB_HOST: git.trader.community
    GITLAB_PORT: 443
    GITLAB_SSH_PORT: 10022

    GITLAB_NOTIFY_ON_BROKEN_BUILDS: "true"
    GITLAB_NOTIFY_PUSHER: "false"

    GITLAB_EMAIL: info@rails-experts.com
    GITLAB_EMAIL_REPLY_TO: noreply@rails-experts.com
    GITLAB_INCOMING_EMAIL_ADDRESS: info@rails-experts.com

    OAUTH_GITHUB_API_KEY: 72401020ebe8bcdcdbe8
    OAUTH_FACEBOOK_APP_SECRET: efda2f9f812c82b245a2969db9fa3701866f2293

    GITLAB_BACKUPS: daily
    GITLAB_BACKUP_TIME: 01:00

    SMTP_ENABLED: "true"
    SMTP_DOMAIN: git.trader.community
    SMTP_HOST: smtp.sendgrid.net
    SMTP_PORT: 587
    SMTP_USER: malagant
    SMTP_PASS: AXE7OO3Hw8@WMTZL
    SMTP_STARTTLS: "true"
    SMTP_AUTHENTICATION: login

    IMAP_ENABLED: "false"
    IMAP_HOST: imap.gmail.com
    IMAP_PORT: 993
    IMAP_USER: mailer@example.com
    IMAP_PASS: password
    IMAP_SSL: "true"
    IMAP_STARTTLS: "false"
  volumes:
    - /home/deploy/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /home/deploy/gitlab/redis:/var/lib/redis
